Repository crmpiperun/piperun-extractor, pull requests merged in 2025-02, with the labels that each got.

#1 PipeRun Extractor v1.0.1
  .gitignore
  README.md
  piperun/cli.py
  piperun/extractor.py
  piperun/schema/companies.py
  piperun/schema/deals.py
  piperun/schema/goals.py
  piperun/schema/person.py
  piperun/utils.py
  pyproject.toml
Labels: enhancement

#2 feat(extractor): add filter updated_at
  piperun/extractor.py
  pyproject.toml
Labels: SWAT: Feature

#3 docs: Improved Documentation
  README.md
Labels: SWAT: Stuff

#4 PipeRun Extractor v1.0.3
  README.md
  piperun/extractor.py
  piperun/schema/custom_fields.py
  piperun/schema/custom_forms.py
  pyproject.toml
Labels: SWAT: Feature
